// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "window.h"

Fl_Menu_Item UserInterface::menu_inputTipo[] = {
 {"Integer", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Float", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"String", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* UserInterface::Integer = UserInterface::menu_inputTipo + 0;
Fl_Menu_Item* UserInterface::Float = UserInterface::menu_inputTipo + 1;
Fl_Menu_Item* UserInterface::String = UserInterface::menu_inputTipo + 2;

UserInterface::UserInterface() {
  { w = new Fl_Double_Window(520, 490, "Simple CRUD");
    w->user_data((void*)(this));
    { inputTitle = new Fl_Input(80, 26, 250, 24, "Titulo");
    } // Fl_Input* inputTitle
    { inputId = new Fl_Input(349, 25, 90, 24, "Id");
    } // Fl_Input* inputId
    { inputField = new Fl_Input(80, 55, 360, 24, "Campo");
    } // Fl_Input* inputField
    { inputType = new Fl_Input(80, 61, 360, 24, "Type");
      inputType->hide();
      inputType->deactivate();
    } // Fl_Input* inputType
    { inputTipo = new Fl_Input_Choice(80, 85, 360, 25, "Tipo");
      inputTipo->menu(menu_inputTipo);
    } // Fl_Input_Choice* inputTipo
    { btnClear = new Fl_Button(24, 132, 100, 25, "Clear");
    } // Fl_Button* btnClear
    { btnUpdate = new Fl_Button(147, 131, 100, 25, "Update");
    } // Fl_Button* btnUpdate
    { btnDelete = new Fl_Button(270, 131, 100, 25, "Delete");
    } // Fl_Button* btnDelete
    { btnInsert = new Fl_Button(394, 131, 100, 25, "Insert");
    } // Fl_Button* btnInsert
    { btnExport = new Fl_Button(189, 448, 140, 35, "Exportar CSV");
    } // Fl_Button* btnExport
    { Fl_Box* o = new Fl_Box(132, 6, 255, 16, "GERADOR CSV");
      o->labelfont(1);
      o->labelsize(22);
    } // Fl_Box* o
    { browser = new Fl_Browser(24, 166, 470, 277);
      browser->type(2);
    } // Fl_Browser* browser
    w->end();
  } // Fl_Double_Window* w
}
