// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef window_h
#define window_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Input_Choice.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Browser.H>

class UserInterface {
public:
  UserInterface();
protected:
  Fl_Double_Window *w;
  Fl_Input *inputTitle;
  Fl_Input *inputId;
  Fl_Input *inputField;
  Fl_Input *inputType;
public:
  Fl_Input_Choice *inputTipo;
  static Fl_Menu_Item menu_inputTipo[];
  static Fl_Menu_Item *Integer;
  static Fl_Menu_Item *Float;
  static Fl_Menu_Item *String;
protected:
  Fl_Button *btnClear;
  Fl_Button *btnUpdate;
  Fl_Button *btnDelete;
  Fl_Button *btnInsert;
  Fl_Button *btnExport;
  Fl_Browser *browser;
};
#endif
